Develop refactor service
RTUITLab/MicroFileServer pull request #7
Opened 2021-10-28 11:15 UTC by 0B1t322

Refactor service
Delete raw http handlers and divide them on layers: transport layer, middlewares layer and bussines-logic layers.
Refactor .env roles make different env values for role admin and user
Update readme
close #4 Add swagger docs
close #2

2021-11-08 18:54 UTC, CAPCHIK requested changes
Это параметры по умолчанию, а не для разработчика, так что они должны быть в файле `docker-compose.yml`, общем, а не override

2021-11-09 11:31 UTC, CAPCHIK requested changes

2021-11-09 11:31 UTC, CAPCHIK commented on README.md
> +docker-compose -f docker-compose.override.yaml up --build
Файл указывать нет необходимости, просто `docker-compose up --build`, нужно использовать и обычный файл и override, а команда без указания файлов именно это и делает

2021-11-09 11:31 UTC, CAPCHIK commented on src/MicroFileServer/Dockerfile
> +CMD printenv ; ./main
Вроде отказались от этого, и разработчику не особенно надо каждый раз видеть простыню из переменных окружения

2021-11-09 11:31 UTC, CAPCHIK commented on src/MicroFileServer/app/app.go
> +		log.Debug("Running in test mode")
Возможно, стоит сделать более подробное описание, чтобы не ты сам догадывался, что ага, тут пустая строка, а если пустая - писать что-то вроде NONE или такого плана

2021-11-10 12:24 UTC, 0B1t322 commented on src/MicroFileServer/Dockerfile
> +CMD printenv ; ./main
Да этого нет в последнем коммите

2021-11-10 16:35 UTC, CAPCHIK approved these changes
@Suput  Необходимо аккуратно слить в мастер, проверить, что развернулось и ничего не упало

2021-11-12 14:12 UTC, merged